# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 魚閣
subtitle:
description: 
keywords:                   #关键词，可不写(写多个时用 , 隔开)
author: LZQ
language: zh-CN
timezone: 'Asia/Shanghai'   #时区

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://liuziqi77.github.io
root: /
# 文章链接格式
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory 文件目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing 文章 静态页面生成属性
new_post_name: :title.md      # File name of new posts
default_layout: post
titlecase: false              # Transform title into titlecase
external_link: true           # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight: 
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Sakura

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/liuziqi77/liuziqi77.github.io.git
  branch: master


#RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# live2d:
#   enable: true
#   scriptFrom: local
#   pluginRootPath: live2dw/
#   pluginJsPath: lib/
#   pluginModelPath: assets/
#   tagMode: false
#   debug: false
#   model:
#     use: live2d-widget-model-epsilon2_1
#   display:
#     position: right
#     width: 200
#     height: 400
#   mobile:
#     show: true
#   react:
#     opacity: 0.6

# Live2D
live2d:
  model:
    jsonPath: https://cdn.jsdelivr.net/gh/liuziqi77/cdn/live2d/packages/live2d-widget-model-epsilon2_1/assets/Epsilon2.1.model.json
    scale: 1
    # hHeadPos: 0.5
    # vHeadPos: 0.618
  display:
    superSample: 2
    width: 200
    height: 400
    position: left
    hOffset: 0
    vOffset: -40
  mobile:
    show: true
    position: left
    scale: 1
  react:
    opacityDefault: 0.6
    opacityOnHover: 0.2
  dialog:
    enable: false
